### ISSUE TITLE
Switch to new Realtime Database Row

### ISSUE THREAD

**Issue by wave-tv** [wave-tv/wave-tv#1]
Hello Open Source Community,

I need help from someone who knows React and Firebase. I need the embedded video player on the "news" page to switch to the video on the next row in the realtime database, once the first video has finished. Currently, it just plays the newest video. I have included a picture of the Firebase database. Thanks!

![database](https://user-images.githubusercontent.com/42773419/46365482-b4e95100-c646-11e8-9861-0d200b1b00ab.PNG)

**Comment by 9reeno** [comment]
I'll pick this one up! I have experience in both fields.

**Comment by 9reeno** [comment]
Clarification question:

Is there any specific order in which you want the videos to play?

E.g., oldest to newest, or newest to oldest (by date or by appearance in database)?

**Comment by wave-tv** [comment]
@9reeno newest to oldest please... thanks!

**Comment by 9reeno** [comment]
Sorry for dropping off the face of the Earth for a day. Got some stuff to report-

There are two ways we can approach this.
1. Incrementally retrieve video data by indexing the keys (-LNber, -LNpnq) on firebase from 0 to n and using firebase.ref('News/' + i).once(snap => ...) when one video ends to grab the next one

2. Retrieve all video data at once with firebase.ref('News').once(snap => ...), store it in an array locally, play next video in array when one ends 

Method one is more performant since it doesn't pull all of your video data at once, thus using less of your traffic on firebase, but it would require you to upload your documents with a specific key (0 to n) instead of what firebase generates automatically (-LNber)

Method two means that we don't have to worry about renaming keys, but it has the potential to reduce the performance of your site since you'll be pulling the whole list of vids from firebase on every visit.

Let me know what you think, which method you prefer, and I'll commit some code towards this afterwards!

**Comment by wave-tv** [comment]
@9reeno i think that method two would be best for right now... I really appreciate it!

**Comment by mark-bruckert** [comment]
@9reeno Hi... It's me again! (I'm just under a different account) In option 2, if a new video is added to the database while the user is watching, will it play next?

**Comment by 9reeno** [comment]
No. In that case, we'd want to use firebase.ref().on() like in your current repo.

I'm looking at the react-youtube component api- commits coming soon!

**Comment by wave-tv** [comment]
Thanks! I look forward to seeing your commits!

**Comment by 9reeno** [comment]
@mark-bruckert Made changes, check out my PR and let me know what you think!

**Comment by wave-tv** [comment]
@9reeno Looking at it now.

**Comment by 9reeno** [comment]
@wave-tv sorry, had to run an errand, I think I forgot publish the PR. should be up there now!

**Comment by wave-tv** [comment]
@9reeno Merged... Thanks!
